import React, {useState, useMemo, useEffect} from 'react';
import {Plus, X, CaretDown, CalendarBlank, DownloadSimple, Check, ArrowRight, BookmarkSimple, Info, ArrowsClockwise} from '@phosphor-icons/react';
import {OverlapLineChart} from './components/spectrum/line-chart';
import '@fontsource/geist/400.css';
import '@fontsource/geist/500.css';
import '@fontsource/geist/600.css';
import '@fontsource/geist/700.css';
import '@fontsource/geist-mono/400.css';
const ASSETS=[{id:'btc',name:'Bitcoin',symbol:'BTC',color:'#2458ff',missing:[]},{id:'eth',name:'Ethereum',symbol:'ETH',color:'#26303a',missing:[17,45]},{id:'sol',name:'Solana',symbol:'SOL',color:'#7144ed',missing:[19,71,80,82]},{id:'link',name:'Chainlink',symbol:'LINK',color:'#188077',missing:[8,37,60]},{id:'tread',name:'Tread.fi',symbol:'TREAD',color:'#ba4b37',logo:'https://s2.coinmarketcap.com/static/img/coins/64x64/42319.png',missing:[]}];
const end=new Date(Date.now()-86400000).toISOString().slice(0,10);
const initialStart=new Date(Date.parse(end)-89*86400000).toISOString().slice(0,10);
const earliest=new Date(Date.now()-365*86400000).toISOString().slice(0,10);
function dates(start,end){const n=Math.round((new Date(end)-new Date(start))/86400000)+1;return Array.from({length:Math.max(0,Math.min(366,n))},(_,i)=>new Date(+new Date(start)+i*86400000).toISOString().slice(0,10))}
const fmt=d=>new Date(d+'T00:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'});
function Coin({a}){return <span className="coin"><img src={a.logo||'/assets/'+a.id+'.png'} alt=""/>{a.name} <span>({a.symbol})</span></span>}
function App(){
const [nav,setNav]=useState('Research'),[prompt,setPrompt]=useState('Compare Bitcoin, Ethereum and Tread.fi over the last 90 days'),[selected,setSelected]=useState(['btc','eth','tread']),[start,setStart]=useState(initialStart),[finish,setFinish]=useState(end),[currency,setCurrency]=useState('USD'),[interval,setInterval]=useState('Daily'),[add,setAdd]=useState(false),[dateOpen,setDateOpen]=useState(false),[modal,setModal]=useState(null),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[saved,setSaved]=useState([]),[applied,setApplied]=useState({ids:['btc','eth','tread'],start:initialStart,end,currency:'USD',interval:'Daily'});
const showToast=s=>{setToast(s);window.setTimeout(()=>setToast(''),3200)};
const [mode,setMode]=useState("live"),[liveStudy,setLiveStudy]=useState(null),[connection,setConnection]=useState(null),[apiError,setApiError]=useState(""),[proposal,setProposal]=useState(null),[interpreting,setInterpreting]=useState(false),[initialLoading,setInitialLoading]=useState(true);
useEffect(()=>{fetch("/api/status").then(r=>r.json()).then(setConnection).catch(()=>setConnection({unavailable:true}));},[]);
const demoStudy=useMemo(()=>{const all=dates(applied.start,applied.end),days=applied.interval==='Weekly'?all.filter((_,i)=>i%7===0):all;const assets=ASSETS.filter(a=>applied.ids.includes(a.id));const missing=days.filter(d=>assets.some(a=>a.missing.includes(all.indexOf(d))));const curves={btc:[100,101,107,117,113,128,140,132,123,137,151],eth:[100,100,117,110,106,115,108,116,109,126,140],sol:[100,110,114,103,90,100,87,91,89,117,128],link:[100,105,99,106,118,110,121,116,124,120,133],tread:[100,106,93,112,108,122,115,129,138,131,144]};const rows=days.map((date,i)=>{let r={date,index:i,missing:missing.includes(date)};assets.forEach(a=>{let f=i/Math.max(1,days.length-1)*10,k=Math.min(9,Math.floor(f)),v=curves[a.id][k]+(curves[a.id][k+1]-curves[a.id][k])*(f-k);r[a.id]=r.missing?null:Math.round((v+(i?Math.sin(i*2.7+a.id.length)*1.2:0))*100)/100});return r});return{days,all,assets,missing,rows,shared:days.length-missing.length}},[applied]);
const study=mode==='live'&&liveStudy?{...liveStudy,assets:ASSETS.filter(a=>liveStudy.settings.ids.includes(a.id))}:demoStudy;
const isLive=mode==='live'&&!!liveStudy;
const visibleStudy=mode==='demo'||!!liveStudy;
const observed=a=>isLive?study.counts[a.id]:study.days.length-study.days.filter(d=>a.missing.includes(study.all.indexOf(d))).length;
async function post(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw new Error(result.error||'Request failed');return result;}
useEffect(()=>{if(mode!=='live')return;let active=true;const settings={ids:['btc','eth','tread'],start:initialStart,end,currency:'USD',interval:'Daily'};setInitialLoading(true);setApiError('');post('/api/research',settings).then(result=>{if(active){setLiveStudy(result);setApplied(settings)}}).catch(e=>{if(active)setApiError(e.message)}).finally(()=>{if(active)setInitialLoading(false)});return()=>{active=false}},[mode]);
async function interpret(){setInterpreting(true);setApiError('');try{setProposal(await post('/api/interpret',{prompt,current:{ids:selected,start,end:finish,currency,interval}}));setModal('proposal')}catch(e){setApiError(e.message)}finally{setInterpreting(false)}}
async function inspect(){if(selected.length<2){showToast('Select at least two assets to compare.');return}if(!start||!finish||start>finish){showToast('Choose valid start and end dates.');return}if(start<earliest){showToast('Choose a start date within the past year.');return}if((new Date(finish)-new Date(start))/86400000>365){showToast('Choose a range up to 366 days.');return}setBusy(true);setApiError('');const settings={ids:[...selected],start,end:finish,currency,interval};try{if(mode==='live'){const result=await post('/api/research',settings);setLiveStudy(result)}setApplied(settings);setModal('coverage')}catch(e){setApiError(e.message)}finally{setBusy(false)}}
function exportStudy(){const record={title:isLive?'Overlap — CMC comparison':'Overlap — illustrative comparison',dataMode:isLive?'CoinMarketCap historical USD price quotes near 23:59 UTC':'Synthetic demo observations',provenance:isLive?study.provenance:null,raw:isLive?study.raw:null,excluded:isLive?study.excluded:null,...applied,sharedDates:study.days.filter(d=>!study.missing.includes(d)),excludedDates:study.missing,observations:study.rows,method:'Index = price / first shared price * 100. Quotes requested near 23:59 UTC; missing dates are not filled; weekly sampling takes every seventh requested date.'};const u=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=isLive?'overlap-cmc-study.json':'overlap-demo-study.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),10000);showToast('Study record exported.')}
return <><header><button className="brand" onClick={()=>setNav('Research')}><img src="/assets/overlap-mark.webp" alt=""/>overlap</button><nav>{['Research','Saved studies','Method'].map(n=><button key={n} onClick={()=>setNav(n)} className={nav===n?'active':''}>{n}{n==='Saved studies'&&saved.length>0&&<small>{saved.length}</small>}</button>)}</nav><button className="demo-menu" onClick={()=>setModal('demo')}>{mode==='demo'?'Demo workspace':'CMC workspace'} <CaretDown size={15}/></button></header>
{nav==='Research'?<div className="workspace"><aside><h2>Your research</h2><textarea aria-label="Research question" value={prompt} onChange={e=>setPrompt(e.target.value)}/><button className="text-button interpret" onClick={interpret} disabled={interpreting}>{interpreting?'Interpreting…':'Interpret with Jev'} <ArrowRight size={14}/></button><p className="caption prompt-caption">{connection?.jevConfigured?'Review proposed settings before applying.':'Jev needs a connection. Manual controls work.'}</p><div className="rule"/><label className="field-label">Assets</label><div className="assets">{selected.map(id=>{const a=ASSETS.find(x=>x.id===id);return <div className="asset" key={id}><Coin a={a}/><button aria-label={'Remove '+a.name} onClick={()=>setSelected(selected.filter(x=>x!==id))}><X size={16}/></button></div>})}</div><button className="text-button add" onClick={()=>setAdd(!add)}><Plus size={18}/> Add asset</button>{add&&<div className="asset-picker">{ASSETS.filter(a=>selected.length<4&&!selected.includes(a.id)).map(a=><button key={a.id} onClick={()=>{setSelected([...selected,a.id]);setAdd(false)}}><Coin a={a}/><Plus size={16}/></button>)}{selected.length===4&&<p>Maximum four assets selected.</p>}</div>}
<div className="field date-field"><label className="field-label">Date interval</label><button className="select date-button" onClick={()=>setDateOpen(!dateOpen)}><CalendarBlank size={18}/><span>{start} — {finish}</span><CaretDown size={14}/></button>{dateOpen&&<div className="date-edit"><label>Start<input aria-label="Start date" type="date" value={start} min={earliest} max={finish} onChange={e=>setStart(e.target.value)}/></label><label>End<input aria-label="End date" type="date" value={finish} min={start} max={end} onChange={e=>setFinish(e.target.value)}/></label><button className="text-button" onClick={()=>setDateOpen(false)}>Done <Check/></button></div>}</div>
<div className="field"><label className="field-label" htmlFor="currency">Currency</label><select id="currency" value={currency} onChange={e=>setCurrency(e.target.value)}><option>USD</option></select></div><div className="field"><label className="field-label" htmlFor="interval">Observations</label><select id="interval" value={interval} onChange={e=>setInterval(e.target.value)}><option>Daily</option><option>Weekly</option></select></div><button className="primary inspect" onClick={inspect} disabled={busy||(mode==='live'&&initialLoading)}>{busy||mode==='live'&&initialLoading?<><ArrowsClockwise className="spin"/>Loading CMC data…</>:'Inspect coverage'}</button><div className="mascot"><img src="/assets/bracket.webp" alt="Bracket mascot"/><span>Your assumptions stay visible.</span></div></aside>
<main><div className="title-row"><div><h1>Same dates. Clearer comparisons.</h1><p className="subtitle">{isLive?'CoinMarketCap · USD quote near 23:59 UTC · Retrieved '+new Date(study.provenance.fetchedAt).toLocaleString():mode==='demo'?'Illustrative demo data · Not live prices.':initialLoading?'Fetching historical prices from CoinMarketCap…':'Historical research · Awaiting a successful data request.'}</p></div><button className="text-button export" onClick={exportStudy} disabled={!visibleStudy}>Export study <DownloadSimple size={16}/></button></div>{apiError&&<div className="api-error" role="alert">{apiError}{isLive&&' The previous successful comparison remains displayed.'}</div>}{!visibleStudy&&<div className="connection-empty"><h2>Compare real observations.</h2><p>{initialLoading?'Loading the 90-day BTC / ETH / TREAD comparison from CoinMarketCap…':connection?.cmcConfigured?'Choose your settings and inspect coverage.':'CoinMarketCap is not connected yet. Add the server API key to enable historical data.'}</p><button className="text-button" onClick={()=>{setMode('demo');setApiError('')}}>Explore the labeled demo</button></div>}{visibleStudy&&<><div className="stats"><span>Requested: <b>{study.days.length} observations</b></span><span>Shared observations: <b>{study.shared} observations</b></span><button onClick={()=>setModal('coverage')} className="missing">Missing: <b>{study.missing.length} observations</b></button></div>
<section className="chart-section"><div className="chart-header"><div><h3>Normalized index</h3><p className="caption">{study.shared?<>All assets start at 100 on {isLive?study.baseline:study.days[0]} (first shared date).</>:'No shared observations. Nothing can be normalized.'}</p></div><div className="legend">{study.assets.map((a,i)=><span key={a.id}><i style={{borderColor:a.color,borderTopStyle:i===0?'solid':i===1?'dashed':'dotted'}}/>{a.symbol}</span>)}</div></div><OverlapLineChart data={study.rows} assets={study.assets} interval={applied.interval} formatDate={fmt}/></section>
<div className="table-scroll"><table><thead><tr><th>Asset</th><th>Observed points</th><th>Missing points</th><th>Period (UTC)</th></tr></thead><tbody>{study.assets.map(a=>{const n=study.days.length-observed(a);return <tr key={a.id}><td><Coin a={a}/></td><td>{study.days.length-n}</td><td>{n}</td><td>{applied.start} — {applied.end}</td></tr>})}</tbody></table></div><footer>{isLive?'Source: CoinMarketCap · Shared UTC dates only.':'Synthetic demo observations · Shared dates only.'} <button onClick={()=>setNav('Method')}>View method <ArrowRight size={13}/></button></footer></>}</main></div>:<section className="secondary"><p className="eyebrow">OVERLAP / {nav.toUpperCase()}</p><h1>{nav==='Method'?'Every comparison, accounted for.':'Your research, within reach.'}</h1>{nav==='Method'?<><p className="lead">A clear record of what went into a comparison—and what stayed out.</p><div className="method-grid">{[['01','Confirm the question','Select the assets, dates and observation interval. Jev proposes supported settings. Confirm them yourself, or use the manual controls.'],['02','Inspect the gaps','Missing observations remain missing. The shared set contains only dates on which every selected asset has a valid positive USD historical price quote.'],['03','Use the same starting point','Historical USD price quotes requested near 23:59 UTC are divided by the first shared price and multiplied by 100. These are not OHLCV daily closes. Weekly sampling takes every seventh requested date; missing dates stay blank.'],['04','Keep the evidence','Export a JSON study with its settings, observations and excluded dates. Live studies retain returned prices and retrieval provenance. A missing observation does not establish why the provider omitted it. Provider errors stop the request.']].map(([n,t,p])=><article key={n}><span>{n}</span><h2>{t}</h2><p>{p}</p></article>)}</div><button className="primary" onClick={()=>setNav('Research')}>Back to research <ArrowRight/></button></>:saved.length?<div className="saved-list">{saved.map((s,i)=><button key={i} onClick={()=>{setMode('live');setLiveStudy(null);setApiError('');setApplied(s);setSelected(s.ids);setStart(s.start);setFinish(s.end);setInterval(s.interval);setNav('Research')}}><BookmarkSimple size={22}/><div><h3>{s.ids.map(x=>x.toUpperCase()).join(' / ')}</h3><p>{fmt(s.start)} — {fmt(s.end)}, 2026 · {s.interval} · Settings only</p></div><ArrowRight/></button>)}</div>:<div className="empty"><BookmarkSimple size={48} weight="thin"/><h2>No studies saved yet.</h2><p>Inspect a comparison and save its settings here.<br/>Studies remain available while this page is open.</p><button className="primary" onClick={()=>setNav('Research')}>Start a comparison <ArrowRight/></button></div>}</section>}
{modal&&<div className="overlay" onClick={()=>setModal(null)}><section className="dialog" role="dialog" aria-modal="true" aria-label={modal==='coverage'?'Coverage review':modal==='proposal'?'Review Jev proposal':'Data connection'} onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={21}/></button>{modal==='proposal'?<><p className="eyebrow">JEV / REVIEW REQUIRED</p><h2>Is this your question?</h2><p>{proposal.proposal.ids.join(' / ').toUpperCase()}<br/>{proposal.proposal.start} — {proposal.proposal.end}<br/>USD · {proposal.proposal.interval==='Weekly'?'Every seventh daily quote':'Daily quotes'}</p><p className="caption">{proposal.warning}</p><button className="primary" onClick={()=>{const s=proposal.proposal;setSelected(s.ids);setStart(s.start);setFinish(s.end);setInterval(s.interval);setModal(null);showToast('Settings applied. Inspect coverage to run the comparison.')}}>Confirm settings</button></>:modal==='demo'?<><Info size={30} color="#2458ff"/><h2>Choose your data source.</h2><p>CMC history: {connection?.cmcConfigured?'key configured; access checked on request':'not connected'}<br/>Jev: {connection?.jevConfigured?'key configured':'not connected'}</p><p className="caption">Live mode never substitutes demo prices. Demo mode remains explicitly labeled.</p><button className="primary" onClick={()=>{setMode('live');setLiveStudy(null);setApiError('');setModal(null)}}>Use CoinMarketCap history</button><button className="save-study" onClick={()=>{setMode('demo');setApiError('');setModal(null)}}>Use illustrative demo</button></>:<><p className="eyebrow">COVERAGE REVIEW</p><h2>Before you compare.</h2><p>{study.days.length} requested observations. <strong>{study.shared} shared.</strong><br/>{study.missing.length} dates will be excluded from every series.</p><div className="coverage-list">{study.assets.map(a=><div key={a.id}><Coin a={a}/><span>{observed(a)} observed</span></div>)}</div><p className="caption">No missing values filled. {isLive?'CoinMarketCap historical observations.':'Illustrative demo data.'}</p><button className="primary" disabled={!study.shared} onClick={()=>{setModal(null);showToast('Comparison uses only the shared observations shown.')}}>Compare {study.shared} shared observations <ArrowRight/></button><button className="save-study" onClick={()=>{setSaved([...saved,{...applied}]);setModal(null);showToast('Study saved for this session.')}}><BookmarkSimple/> Save study settings</button></>}</section></div>}{toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}</>}
export { App }; export default App;
